server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React SPA — todas las rutas desconocidas van a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Django static files — ya copiados en /usr/share/nginx/html/static
    location /static/ {
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
